version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "main"
    directories:
      - "/"
      - "/spring-boot-starter-data-reindexer"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-upgrade"
